module.exports = {
	"colors": [{
		"name": "redbase",
		"color": "#F44336"
	}, {
		"name": "pinkbase",
		"color": "#e91e63"
	}, {
		"name": "purplebase",
		"color": "#9c27b0",
	}, {
		"name": "deeppurplebase",
		"color": "#673ab7",
	}, {
		"name": "indigobase",
		"color": "#3f51b5",
	}, {
		"name": "bluebase",
		"color": "#2196F3",
	}, {
		"name": "lightbluebase",
		"color": "#03a9f4",
	}, {
		"name": "cyanbase",
		"color": "#00bcd4",
	}, {
		"name": "tealbase",
		"color": "#009688",
	}, {
		"name": "greenbase",
		"color": "#4CAF50",
	}, {
		"name": "lightgreenbase",
		"color": "#8bc34a",
	}, {
		"name": "limebase",
		"color": "#cddc39",
	}, {
		"name": "yellowbase",
		"color": "#ffeb3b",
	}, {
		"name": "amberbase",
		"color": "#ffc107",
	}, {
		"name": "orangebase",
		"color": "#ff9800",
	}, {
		"name": "deeporangebase",
		"color": "#ff5722",
	}, {
		"name": "brownbase",
		"color": "#795548",
	}, {
		"name": "bluegreybase",
		"color": "#607d8b",
	}, {
		"name": "greybase",
		"color": "#9e9e9e",
	}, {
		"name": "white",
		"color": "#ffffff",
	}, {
		"name": "black",
		"color": "#000000",
	}, {
		"name": "transparent",
		"color": "transparent",
	}],
	"colorSets": [{
		"name": "singleComplementary69bc38",
		"colors": [{
			"color": "#69bc38"
		}, {
			"color": '#94dd69'
		}, {
			"color": '#a8dd88'
		}, {
			"color": '#c53b5b'
		}, {
			"color": '#5e8d43'
		}, {
			"color": '#944658'
		}, {
			"color": '#397a12'
		}, {
			"color": '#80132c'
		}, {
			"color": '#e26b87'
		}, {
			"color": '#e28b9f'
		}]
	},{
		"name": "singleadcd83",
		"colors": [{
			"color": "#adcd83"
		}, {
			"color": '#cbe6a8'
		}, {
			"color": '#d2e6b8'
		}, {
			"color": '#5e852b'
		}, {
			"color": '#889a70'
		}]
	}],
}
